string_example="Manisha"
string_changed="-".join(string_example)
string_changed1="\n".join(string_example)
string_changed2="\t".join(string_example)
print(string_changed)
print(string_changed1)
print(string_changed2)
print(string_example.center(20))
print(string_example.zfill(20))